[package]
name = "ptx"
version = "0.0.1"
authors = []

[lib]
name = "uu_ptx"
path = "ptx.rs"

[dependencies]
getopts = "0.2"
libc = "0.2"
aho-corasick = "0.6"
memchr = "1.0"
regex-syntax = "0.4"
regex = "0.2"
uucore = { path="../uucore" }

[[bin]]
name = "ptx"
path = "main.rs"
